--- #YAML:1.0
name:               OpenTok-API
version:            0.02
abstract:           Perl SDK for OpenTok
author:
    - Maxim Nikolenko <root@zbsd.ru>
license:            BSD
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Digest::HMAC_SHA1:  0
    Exception::Class:   0
    LWP:                0
    MIME::Base64:       0
    Test::More:         0
    Time::HiRes:        0
    XML::XPath:         0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
